name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: GroceryStoreSystem-Backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: GroceryStoreSystem-Backend
  frontend:
     # needs: backend
      runs-on: Windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: push frontend
          uses: akhileshns/heroku-deploy@v3.12.12 
          with:
            heroku_api_key: '678de1b4-6da9-438e-800c-70f13d302580'
            heroku_app_name: "grocerystoresys-frontend-22ws" 
            heroku_email: "onyekachi.ezekwem@mail.mcgill.ca"
            dontuseforce: false
